# Generated by Django 5.2.18 on 2026-10-07 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationjob',
            name='provider_submission_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
