# Generated by Django 5.2.18 on 2026-10-07 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('jobs', '0002_generationjob_provider_submission_started_at'),
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='generationjob',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_job_id', ''), _negated=True), fields=('provider_name', 'provider_job_id'), name='unique_provider_job_identifier'),
        ),
    ]
