# Generated by Django 5.2.18 on 2026-10-07 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_generationjob_unique_provider_job_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationjob',
            name='next_poll_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='poll_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
