# Generated by Django 5.2.18 on 2026-10-07 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_generationjob_next_poll_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationjob',
            name='submission_resolution',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
