# Generated by Django 5.2.18 on 2026-10-08 08:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('jobs', '0005_generationjob_submission_resolution'),
        ('studio', '0002_export'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationQuote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payload', models.JSONField()),
                ('snapshot', models.JSONField()),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='generationjob',
            name='accepted_quote',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='asset_attempt_token',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='asset_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='asset_cleanup_keys',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='asset_error_code',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='asset_lease_until',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='asset_next_attempt_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='asset_status',
            field=models.CharField(default='not_requested', max_length=24),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='dispatch_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='generated_asset',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_job', to='studio.asset'),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='provider_reported_credits',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='generationjob',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('workspace', 'requested_by', 'idempotency_key'), name='unique_generation_submit_attempt'),
        ),
        migrations.AddField(
            model_name='generationquote',
            name='job',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.generationjob'),
        ),
        migrations.AddField(
            model_name='generationquote',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generationquote',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.workspace'),
        ),
    ]
