# Generated by Django 5.2.18 on 2026-10-08 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_generationquote_generationjob_accepted_quote_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedFileCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_key', models.CharField(max_length=255, unique=True)),
                ('attempt_token', models.CharField(max_length=32)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.generationjob')),
            ],
        ),
    ]
