# Generated by Django 5.2.18 on 2026-10-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_generatedfilecandidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedfilecandidate',
            name='cleanup_after',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='generationquote',
            name='consumed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
