# Generated by Django 5.2.18 on 2026-10-07 23:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=24)),
                ('format', models.CharField(choices=[('9:16', '9:16'), ('16:9', '16:9')], max_length=16)),
                ('output_path', models.CharField(blank=True, max_length=255)),
                ('subtitle_path', models.CharField(blank=True, max_length=255)),
                ('settings', models.JSONField(default=dict)),
                ('manifest', models.JSONField(default=dict)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('attempt_token', models.CharField(blank=True, max_length=32)),
                ('lease_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('next_attempt_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('cleanup_keys', models.JSONField(blank=True, default=list)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='studio.project')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
