# Generated by Django 5.2.18 on 2026-10-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0004_characters'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ai_disclosure',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio')], max_length=32),
        ),
    ]
